# Generated by Django 3.1 on 2022-06-22 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220619_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.CharField(default='Add Company address', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='Add Company Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='placement',
            name='placement_title',
            field=models.CharField(default='Add Bid-item Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='placementbid',
            name='offer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placementbid',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('order_id', models.IntegerField()),
                ('order_status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.myuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
